### ISSUE TITLE
Does the spotlight search work if this app is sandboxed?

### ISSUE THREAD

**Issue by saltzmanjoelh** [HIIT/JustUsed#7]
I'm trying to find a way to access some of the sfl files in a sandboxed app.

**Comment by MarcoFiletti** [comment]
I doubt that it will work, since it needs access to many files spread across the system, all outside the sandbox. If you know in advance which sfl file(s) you need, the only think I can think of is using an OpenPanel to point to the file(s) in question so that the user manually grants you access. Then an app-scoped bookmark can be used to retrieve info from that file(s) only.
